version: '3.8'
services:
  myself:
    build: .
    restart: always
    ports:
      - 8080:8080
  temporal-postgresql:
    environment:
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_USER=temporal
    image: postgres:14.5
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  temporal-server:
    depends_on:
      temporal-postgresql:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:${TEMPORAL_SERVER_TAG:-1.18.5}
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "tctl",
          "--address",
          "temporal-server:7233",
          "workflow",
          "list"
        ]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - 7233:7233
    volumes:
      - ./config/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    depends_on:
      temporal-server:
        condition: service_healthy
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal-server:7233
    image: temporalio/admin-tools:${TEMPORAL_SERVER_TAG:-1.18.5}
    restart: always
    stdin_open: true
    tty: true
  temporal-web:
    depends_on:
      temporal-server:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7233
    image: temporalio/ui:${TEMPORAL_WEB_TAG:-2.9.1}
    restart: always
    ports:
      - "10000:8080"
